name: Auto Approve and Merge PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from PR (Safe Checkout)
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Validate PR
      run: |
        AUTHOR_NAME="${{ github.actor }}"
        FILE_PATH="community/$AUTHOR_NAME.md"
        
        if [[ ! -f $FILE_PATH ]]; then
            echo "ERROR: Expected a file at $FILE_PATH, but it doesn't exist."
            exit 1
        fi
        
    - name: Post Comment if Validation Fails
      if: failure()
      run: |
        echo "Ei! Parece que algo n√£o deu certo com o seu PR. Ele deve conter apenas um arquivo .md na pasta 'community/', e o nome desse arquivo deve ser o mesmo que o seu nome de usu√°rio no GitHub. D√™ uma olhada nas instru√ß√µes no README.md e no CONTRIBUTE.md para acertar. Assim que fizer as corre√ß√µes, atualize o PR para que possamos avali√°-lo novamente. Se continuar com problemas, infelizmente a revis√£o ser√° manual e pode demorar um pouquinho. Valeu pela contribui√ß√£o üëäüòâ" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt

    - name: Approve and Comment PR
      if: success()
      run: |
        echo "E a√≠! Seu PR com o arquivo .md na pasta 'community/' est√° perfeito e j√° foi aprovado! Muito obrigado por se juntar √† comunidade üöÄ" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge PR
      uses: pascalgn/automerge-action@v0.15.6
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_COMMIT_MESSAGE: "Merged: Inclus√£o do perfil ${{ github.actor }}"
        MERGE_METHOD: "squash"
